### ISSUE TITLE
Error in `CorrFitter` when doing Bootstrap 

### ISSUE THREAD

**Issue by erinaldi** [gplepage/corrfitter#2]
With the latest releases of `gvar`, `lsqfit` and `corrfitter` (and also with a combination of the previous versions) I get an error when using the `bootstrap_iter` method of the `CorrFitter` class.

For example, going through the "Bootstrap" example in the `corrfitter` manual (Sec. 1.13), the line
* for bs_fit in fitter.bootstrap_iter(bs_datalist): # bs_fit = lsqfit output
fails with 

```~/.local/lib/python3.6/site-packages/corrfitter.py in bootstrap_iter(self, datalist, n)
   1145             datalist = (self.builddata(d, self.prior)
   1146                         for d in datalist)
-> 1147         for bs_fit in self.fit.bootstrap_iter(n, datalist=datalist):
   1148             yield bs_fit
   1149 

~/.local/lib/python3.6/site-packages/lsqfit/__init__.py in bootstrapped_fit_iter(self, n, datalist)
   1297             else:
   1298                 piter = _gvar.bootstrap_iter(prior)
-> 1299                 for datab in datalist:
   1300                     fit = nonlinear_fit(
   1301                         data=datab, prior=next(piter), p0=self.pmean, **fargs

~/.local/lib/python3.6/site-packages/corrfitter.py in <genexpr>(.0)
   1144         if datalist is not None:
   1145             datalist = (self.builddata(d, self.prior)
-> 1146                         for d in datalist)
   1147         for bs_fit in self.fit.bootstrap_iter(n, datalist=datalist):
   1148             yield bs_fit

AttributeError: 'CorrFitter' object has no attribute 'prior'
```

Inspecting the code `corrfitter.py` I notice that the 
```
datalist = (self.builddata(d, self.prior) for d in datalist)
```
line is calling a `CorrFitter.buildata` function with 2 arguments, but there is no such function defined.

Should `self.prior` be removed from that line?

**Comment by gplepage** [comment]
Yes, it is broken (as is my testing, evidently). It isn't simple to fix and so will take a couple of day. I will try to have it done by the weekend. Thanks for reporting the problem.

**Comment by gplepage** [comment]
To use the bootstrap, you need to update `` lsqfit`` to v9.3 (or later) and also update ``corrfitter`` to v6.0.7 (or later). This should work as advertised. 

I added a working bootstrap example to the end of the ``etas.py`` script in the examples file.

**Comment by erinaldi** [comment]
Thanks. I confirm that the example is working, and my usage of the function is also working.
Closing now.
